--------------------------------------------------------
--  File created - Saturday-March-30-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUSINESS
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."BUSINESS" 
   (	"PROVIDER_ID" VARCHAR2(12 BYTE), 
	"CONTACT_NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER, 
	"INVENTORY" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."EMPLOYEE" 
   (	"EMPLOYEE_ID" VARCHAR2(12 BYTE), 
	"EMPLOYEE_NAME" VARCHAR2(100 BYTE), 
	"EMPLOYEE_LOCATION" VARCHAR2(1000 BYTE), 
	"AGE" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INDIVIDUAL
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."INDIVIDUAL" 
   (	"PROVIDER_ID" VARCHAR2(12 BYTE), 
	"AGE" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."INVENTORY" 
   (	"INVENTORY_ID" VARCHAR2(20 BYTE), 
	"INVENTORY_LOCATION" VARCHAR2(1000 BYTE), 
	"PRODUCT_CONDITION" VARCHAR2(20 BYTE), 
	"CHECK_IN_DATE" DATE, 
	"CHECK_OUT_DATE" DATE, 
	"CHECK_IN_ID" VARCHAR2(20 BYTE), 
	"CHECK_OUT_ID" VARCHAR2(20 BYTE), 
	"MODEL_NUMBER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANUFACTURER
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."MANUFACTURER" 
   (	"PROVIDER_ID" VARCHAR2(12 BYTE), 
	"MANUFACTURER_ID" VARCHAR2(12 BYTE), 
	"CONTACT_NAME" VARCHAR2(100 BYTE), 
	"CONTACT_PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NON_FORMAL
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."NON_FORMAL" 
   (	"EMPLOYEE_ID" VARCHAR2(20 BYTE), 
	"COLLECTION_SOURCE" VARCHAR2(1000 BYTE), 
	"PRODUCT_TYPE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_INFO
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."ORDER_INFO" 
   (	"ORDER_ID" VARCHAR2(20 BYTE), 
	"TRANSPORT_ID" VARCHAR2(20 BYTE), 
	"ORDER_SOURCE" VARCHAR2(1000 BYTE), 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROCESSOR
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."PROCESSOR" 
   (	"PROCESSOR_ID" VARCHAR2(12 BYTE), 
	"PROCESSOR_NAME" VARCHAR2(100 BYTE), 
	"BALANCE" NUMBER, 
	"PROCESSOR_LOCATION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVIDER
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."PROVIDER" 
   (	"PROVIDER_ID" VARCHAR2(12 BYTE), 
	"PROVIDER_NAME" VARCHAR2(100 BYTE), 
	"PROVIDER_LOCATION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECYCLER
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."RECYCLER" 
   (	"PROCESSOR_ID" VARCHAR2(12 BYTE), 
	"RECYCLER_SPECIALITY" VARCHAR2(30 BYTE), 
	"RECYCLER_CAPABILITY" NUMBER, 
	"RECYCLER_CURRENT" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALE_ORDER
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."SALE_ORDER" 
   (	"SELLER_ID" VARCHAR2(12 BYTE), 
	"SELLER_NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	"SELLER_LOCATION" VARCHAR2(1000 BYTE), 
	"BUYER_LOCATION" VARCHAR2(1000 BYTE), 
	"BUYER_ID" VARCHAR2(20 BYTE), 
	"BUYER_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSPORT
--------------------------------------------------------

  CREATE TABLE "C##RIDAY"."TRANSPORT" 
   (	"EMPLOYEE_ID" VARCHAR2(12 BYTE), 
	"ORDER_ID" VARCHAR2(20 BYTE), 
	"SOURCE" VARCHAR2(1000 BYTE), 
	"DESTINATION" VARCHAR2(1000 BYTE), 
	"TRANSPORT_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into C##RIDAY.BUSINESS
SET DEFINE OFF;
REM INSERTING into C##RIDAY.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into C##RIDAY.INDIVIDUAL
SET DEFINE OFF;
REM INSERTING into C##RIDAY.INVENTORY
SET DEFINE OFF;
REM INSERTING into C##RIDAY.MANUFACTURER
SET DEFINE OFF;
REM INSERTING into C##RIDAY.NON_FORMAL
SET DEFINE OFF;
REM INSERTING into C##RIDAY.ORDER_INFO
SET DEFINE OFF;
REM INSERTING into C##RIDAY.PROCESSOR
SET DEFINE OFF;
REM INSERTING into C##RIDAY.PROVIDER
SET DEFINE OFF;
REM INSERTING into C##RIDAY.RECYCLER
SET DEFINE OFF;
REM INSERTING into C##RIDAY.SALE_ORDER
SET DEFINE OFF;
REM INSERTING into C##RIDAY.TRANSPORT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BUSINESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."BUSINESS_PK" ON "C##RIDAY"."BUSINESS" ("PROVIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."EMPLOYEE_PK" ON "C##RIDAY"."EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDIVIDUAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."INDIVIDUAL_PK" ON "C##RIDAY"."INDIVIDUAL" ("PROVIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INVENTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."INVENTORY_PK" ON "C##RIDAY"."INVENTORY" ("INVENTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANUFACTURER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."MANUFACTURER_PK" ON "C##RIDAY"."MANUFACTURER" ("PROVIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NON_FORMAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."NON_FORMAL_PK" ON "C##RIDAY"."NON_FORMAL" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."ORDER_PK" ON "C##RIDAY"."ORDER_INFO" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROCESSOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."PROCESSOR_PK" ON "C##RIDAY"."PROCESSOR" ("PROCESSOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVIDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."PROVIDER_PK" ON "C##RIDAY"."PROVIDER" ("PROVIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECYCLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."RECYCLER_PK" ON "C##RIDAY"."RECYCLER" ("PROCESSOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."SALE_ORDER_PK" ON "C##RIDAY"."SALE_ORDER" ("SELLER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##RIDAY"."TRANSPORT_PK" ON "C##RIDAY"."TRANSPORT" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."EMPLOYEE" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INDIVIDUAL
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."INDIVIDUAL" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."INDIVIDUAL" ADD CONSTRAINT "INDIVIDUAL_PK" PRIMARY KEY ("PROVIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."INVENTORY" MODIFY ("INVENTORY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."INVENTORY" MODIFY ("INVENTORY_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."INVENTORY" ADD CONSTRAINT "INVENTORY_PK" PRIMARY KEY ("INVENTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NON_FORMAL
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."NON_FORMAL" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."NON_FORMAL" MODIFY ("COLLECTION_SOURCE" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."NON_FORMAL" ADD CONSTRAINT "NON_FORMAL_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_INFO
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."ORDER_INFO" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."ORDER_INFO" MODIFY ("ORDER_SOURCE" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."ORDER_INFO" ADD CONSTRAINT "ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANUFACTURER
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."MANUFACTURER" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."MANUFACTURER" MODIFY ("MANUFACTURER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."MANUFACTURER" ADD CONSTRAINT "MANUFACTURER_PK" PRIMARY KEY ("PROVIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSPORT
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."TRANSPORT" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."TRANSPORT" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."TRANSPORT" ADD CONSTRAINT "TRANSPORT_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROCESSOR
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."PROCESSOR" MODIFY ("PROCESSOR_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."PROCESSOR" ADD CONSTRAINT "PROCESSOR_PK" PRIMARY KEY ("PROCESSOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALE_ORDER
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."SALE_ORDER" MODIFY ("SELLER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."SALE_ORDER" ADD CONSTRAINT "SALE_ORDER_PK" PRIMARY KEY ("SELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECYCLER
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."RECYCLER" MODIFY ("PROCESSOR_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."RECYCLER" ADD CONSTRAINT "RECYCLER_PK" PRIMARY KEY ("PROCESSOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUSINESS
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."BUSINESS" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."BUSINESS" ADD CONSTRAINT "BUSINESS_PK" PRIMARY KEY ("PROVIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVIDER
--------------------------------------------------------

  ALTER TABLE "C##RIDAY"."PROVIDER" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."PROVIDER" MODIFY ("PROVIDER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##RIDAY"."PROVIDER" ADD CONSTRAINT "PROVIDER_PK" PRIMARY KEY ("PROVIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
