CREATE OR REPLACE VIEW EMPLOYEE_CHECK(ID,NAME, AGE, SALARY, PHONE, ACCESSLEVEL) AS
(SELECT S.EMPLOYEE_ID,S.NAME,S.AGE,S.SALARY,S.PHONE_NUMBER,S.ACCESSLEVEL FROM EMPLOYEE "S");

CREATE SEQUENCE EMPLOYEE_ID_SEQ
INCREMENT BY 10
START WITH 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER EMPLOYEE_ON_INSERT
  BEFORE INSERT ON EMPLOYEE
  FOR EACH ROW
BEGIN
  SELECT EMPLOYEE_ID_SEQ.nextval
  INTO :new.EMPLOYEE_ID
  FROM dual;
END;

INSERT INTO EMPLOYEE VALUES('','01574623975','Not Riday',50000,21,'notriday@gmail.com','notadmin',5);
INSERT INTO EMPLOYEE VALUES('','01574623975','Not Riday2',50000,22,'notriday@gmail.com2','notadmin2',6);


CREATE TABLE PAPER_TABLE
( EMPLOYEE_ID VARCHAR(20),
  PAPER VARCHAR(1000),

  CONSTRAINT PAPER_TABLE_EMPLOYEE_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE,
  CONSTRAINT PAPER_TABLE_PK PRIMARY KEY(EMPLOYEE_ID,PAPER) );


CREATE OR REPLACE VIEW PAPERS(NAME, UNIVERSITY, COLLABORATOR, PAPER, FUNDING) AS
(SELECT E.NAME,N.UNIVERSITY_NAME,N.PUBLISHER_NAME,P.PAPER,R.FUNDING FROM EMPLOYEE "E" JOIN RESEARCH "R" USING(EMPLOYEE_ID) JOIN PAPER_TABLE "P" USING(EMPLOYEE_ID) JOIN COLLABORATES "C" USING(EMPLOYEE_ID)
JOIN COLLABORATION "N" USING(PUBLISHER_ID));


INSERT INTO Research VALUES('81','Recycling','BsC',10000);
INSERT INTO Research VALUES('91','Recycling','Masters',50000);
INSERT INTO Research VALUES('101','Destroying','Masters',80000);
INSERT INTO Research VALUES('111','Recycling','PhD',60000);
INSERT INTO Research VALUES('121','Refurbishing','PhD',90000);

INSERT INTO EMPLOYEE VALUES('','Recycling','Research1',50000,30,'Research1@gmail.com2','nopro',3);
INSERT INTO EMPLOYEE VALUES('','Recycling','Research2',50000,30,'Research2@gmail.com2','nopro',5);
INSERT INTO EMPLOYEE VALUES('','Destroying','Research3',50000,30,'Research3@gmail.com2','nopro',8);
INSERT INTO EMPLOYEE VALUES('','Recycling','Research4',50000,30,'Research4@gmail.com2','nopro',4);
INSERT INTO EMPLOYEE VALUES('','Refurbishing','Research5',50000,30,'Research5@gmail.com2','nopro',10);

INSERT INTO PAPER_TABLE VALUES('81','ABCD');
INSERT INTO PAPER_TABLE VALUES('81','RYTOH');
INSERT INTO PAPER_TABLE VALUES('81','Akdjf');
INSERT INTO PAPER_TABLE VALUES('81','Akdjf');
INSERT INTO PAPER_TABLE VALUES('91','Akdjf');
INSERT INTO PAPER_TABLE VALUES('101','Trsf');
INSERT INTO PAPER_TABLE VALUES('111','Trsf');
INSERT INTO PAPER_TABLE VALUES('121','Trsf');
INSERT INTO PAPER_TABLE VALUES('121','KJD');
INSERT INTO PAPER_TABLE VALUES('111','DFLhs');


INSERT INTO COLLABORATION VALUES('','Publisher1','England','Oxford','pub@gmail.com','46136466548');
INSERT INTO COLLABORATION VALUES('','Publisher2','England','Oxford','pub2@gmail.com','46138976548');
INSERT INTO COLLABORATION VALUES('','Publisher3','America','Harvard','pub3@gmail.com','8974656');
INSERT INTO COLLABORATION VALUES('','Publisher4','Bangladesh','BUET','pub4@gmail.com','02165713457');
INSERT INTO COLLABORATION VALUES('','Publisher5','Bangladesh','Dhaka University','pub5@gmail.com','02465749716');

INSERT INTO COLLABORATES VALUES('1000000001','81');
INSERT INTO COLLABORATES VALUES('1000000003','91');
INSERT INTO COLLABORATES VALUES('1000000000','101');
INSERT INTO COLLABORATES VALUES('1000000004','111');


CREATE SEQUENCE STATION_ID_SEQ
INCREMENT BY 10
START WITH 1
MAXVALUE 1000000
CACHE 100
NOCYCLE;


CREATE OR REPLACE TRIGGER DUMP_ON_INSERT
  BEFORE INSERT ON DUMP
  FOR EACH ROW
BEGIN
  SELECT STATION_ID_SEQ.nextval
  INTO :new.STATION_ID
  FROM dual;
END;

INSERT INTO DUMP VALUES('','SAVAR',5,100000);
INSERT INTO DUMP VALUES('','CHITTAGONG',2,550000);
INSERT INTO DUMP VALUES('','SAVAR',1,230000);
INSERT INTO DUMP VALUES('','KHULNA',4,850000);
INSERT INTO DUMP VALUES('','BARISHAL',5,600000);
INSERT INTO DUMP VALUES('','DHAKA',6,100000);
INSERT INTO DUMP VALUES('','MIRPUR',1,800000);
INSERT INTO DUMP VALUES('','MIRPUR 12',5,400000);
INSERT INTO DUMP VALUES('','MIRPUR 11',3,100000);
INSERT INTO DUMP VALUES('','SAVAR',5,700000);


CREATE OR REPLACE VIEW EMPLOYEE_DUMP(NAME,PHONE,LOCATION,PRODUCT_TYPE) AS
(SELECT E.NAME,E.PHONE_NUMBER,D.LOCATION,S.PRODUCT_TYPE FROM EMPLOYEE "E" JOIN
DISSEMBLER "S" USING(EMPLOYEE_ID) JOIN DUMPING USING(EMPLOYEE_ID) JOIN
DUMP "D" USING(STATION_ID));


CREATE SEQUENCE INVENTORY_ID_SEQ
INCREMENT BY 100
START WITH 1000000
MAXVALUE 100000000
CACHE 100
NOCYCLE
NOORDER;


CREATE OR REPLACE TRIGGER INVENTORY_ON_INSERT
  BEFORE INSERT ON INVENTORY
  FOR EACH ROW
BEGIN
  SELECT INVENTORY_ID_SEQ.nextval
  INTO :new.INVENTORY_ID
  FROM dual;
END;


CREATE OR REPLACE TRIGGER TRANSPORT_DONE
AFTER UPDATE OF STATUS
ON EMPLOYEE
FOR EACH ROW
WHEN(New.STATUS = 'free')
DECLARE
  orderNumber varchar(20);
  barc varchar(100);
  cond varchar(100);
BEGIN
  SELECT ORDER_ID INTO orderNumber FROM TRANSPORTATION WHERE EMPLOYEE_ID = :old.EMPLOYEE_ID;
  DELETE FROM TRANSPORTATION WHERE EMPLOYEE_ID = :old.EMPLOYEE_ID AND ORDER_ID = orderNumber;
  SELECT BARCODE INTO barc FROM ORDER_PROVIDER WHERE ORDER_ID = orderNumber;
  SELECT PRODUCT_CONDITION INTO cond FROM ORDER_PROVIDER WHERE ORDER_ID = orderNumber;
INSERT INTO INVENTORY VALUES('',:old.EMPLOYEE_ID,'',SYSDATE,barc,'','',cond);
END;

CREATE OR REPLACE TRIGGER INVENTORY_ASK
AFTER INSERT
ON INVENTORY
FOR EACH ROW
DECLARE
  employee varchar(20);
  cond varchar(100);
BEGIN
  cond := :NEW.PRODUCT_CONDITION;
  IF UPPER(cond) = 'VERY GOOD' THEN
    SELECT EMPLOYEE_ID INTO employee FROM DISSEMBLER JOIN EMPLOYEE USING(EMPLOYEE_ID) WHERE UPPER(EMPLOYEE.STATUS) = 'FREE';
    UPDATE EMPLOYEE SET STATUS = 'busy' WHERE EMPLOYEE_ID = employee;
  ELSIF UPPER(cond) = 'BAD' THEN
    SELECT EMPLOYEE_ID INTO employee FROM DISSEMBLER JOIN EMPLOYEE USING(EMPLOYEE_ID) WHERE UPPER(EMPLOYEE.STATUS) = 'FREE';
    UPDATE EMPLOYEE SET STATUS = 'busy' WHERE EMPLOYEE_ID = employee;
  END IF;
END;
