CREATE OR REPLACE VIEW EMPLOYEE_CHECK(NAME, AGE, SALARY, PHONE) AS 
(SELECT S.NAME,S.AGE,S.SALARY,S.PHONE_NUMBER FROM EMPLOYEE "S" WHERE S.ACCESSLEVEL <  6);


CREATE SEQUENCE EMPLOYEE_ID_SEQ
INCREMENT BY 10
START WITH 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER EMPLOYEE_ON_INSERT
  BEFORE INSERT ON EMPLOYEE
  FOR EACH ROW
BEGIN
  SELECT EMPLOYEE_ID_SEQ.nextval
  INTO :new.EMPLOYEE_ID
  FROM dual;
END;

INSERT INTO EMPLOYEE VALUES('','01574623975','Not Riday',50000,21,'notriday@gmail.com','notadmin',5);
INSERT INTO EMPLOYEE VALUES('','01574623975','Not Riday2',50000,22,'notriday@gmail.com2','notadmin2',6);


CREATE TABLE PAPER_TABLE
( EMPLOYEE_ID VARCHAR(20),
  PAPER VARCHAR(1000),
  
  CONSTRAINT PAPER_TABLE_EMPLOYEE_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE,
  CONSTRAINT PAPER_TABLE_PK PRIMARY KEY(EMPLOYEE_ID,PAPER) );
  
 
CREATE OR REPLACE VIEW PAPERS(NAME, UNIVERSITY, PAPER, FUNDING) AS
(SELECT E.NAME,P.PAPER,N.UNIVERSITY_NAME,R.FUNDING FROM EMPLOYEE "E" JOIN RESEARCH "R" USING(EMPLOYEE_ID) JOIN PAPER_TABLE "P" USING(EMPLOYEE_ID) JOIN COLLABORATES "C" USING(EMPLOYEE_ID)
JOIN COLLABORATION "N" USING(PUBLISHER_ID));


INSERT INTO Research VALUES('81','Recycling','BsC',10000);
INSERT INTO Research VALUES('91','Recycling','Masters',50000);
INSERT INTO Research VALUES('101','Destroying','Masters',80000);
INSERT INTO Research VALUES('111','Recycling','PhD',60000);
INSERT INTO Research VALUES('121','Refurbishing','PhD',90000);

INSERT INTO EMPLOYEE VALUES('','Recycling','Research1',50000,30,'Research1@gmail.com2','nopro',3);
INSERT INTO EMPLOYEE VALUES('','Recycling','Research2',50000,30,'Research2@gmail.com2','nopro',5);
INSERT INTO EMPLOYEE VALUES('','Destroying','Research3',50000,30,'Research3@gmail.com2','nopro',8);
INSERT INTO EMPLOYEE VALUES('','Recycling','Research4',50000,30,'Research4@gmail.com2','nopro',4);
INSERT INTO EMPLOYEE VALUES('','Refurbishing','Research5',50000,30,'Research5@gmail.com2','nopro',10);

INSERT INTO PAPER_TABLE VALUES('81','ABCD');
INSERT INTO PAPER_TABLE VALUES('81','RYTOH');
INSERT INTO PAPER_TABLE VALUES('81','Akdjf');
INSERT INTO PAPER_TABLE VALUES('81','Akdjf');
INSERT INTO PAPER_TABLE VALUES('91','Akdjf');
INSERT INTO PAPER_TABLE VALUES('101','Trsf');
INSERT INTO PAPER_TABLE VALUES('111','Trsf');
INSERT INTO PAPER_TABLE VALUES('121','Trsf');
INSERT INTO PAPER_TABLE VALUES('121','KJD');
INSERT INTO PAPER_TABLE VALUES('111','DFLhs');

